@startuml

skinparam handwritten true
skinparam componentstyle rectangle
allowmixing
skinparam titleFontSize 18

skinparam actorStyle Hollow 
skinparam actorBackgroundColor black

!includeurl ../sprites/fire_sky.puml
!includeurl ../sprites/air.puml
!includeurl ../sprites/water.puml
!includeurl ../sprites/earth.puml
!includeurl ../sprites/darkness.puml

!$ICONURL = "../icons/icons"

!include $ICONURL/common.puml
!includeurl $ICONURL/govicons/washington_monument.puml
!includeurl $ICONURL/font-awesome-6/crown.puml
!includeurl $ICONURL/font-awesome-6/landmark.puml
!includeurl $ICONURL/font-awesome-6/landmark_dome.puml
!includeurl $ICONURL/font-awesome-6/monument.puml
!includeurl $ICONURL/font-awesome-6/mosque.puml
!includeurl $ICONURL/font-awesome-6/place_of_worship.puml
!includeurl $ICONURL/font-awesome-6/tent.puml
!includeurl $ICONURL/font-awesome-6/people_group.puml
!includeurl $ICONURL/font-awesome-6/people_line.puml
!includeurl $ICONURL/font-awesome-6/book.puml
!includeurl $ICONURL/font-awesome-6/book_open.puml
!includeurl $ICONURL/font-awesome-6/book_bookmark.puml

!includeurl $ICONURL/font-awesome-6/map.puml
!includeurl $ICONURL/font-awesome-5/magic.puml
!includeurl $ICONURL/font-awesome/thermometer.puml


!define SHRINE(_alias, _label) rectangle "<$monument*.7>\n_label" as _alias
!define MINOR(_alias, _label) rectangle "<$landmark>\n_label" as _alias
!define MAJOR(_alias, _label) rectangle "<$landmark_dome*1.4>\n_label" as _alias
!define GREAT(_alias, _label) rectangle "<$place_of_worship*2>\n_label" as _alias

!define CLAN(_alias, _label) rectangle "<$people_group>\n_label" as _alias
!define TRIBE(_alias, _label) rectangle "<$people_line>\n_label" as _alias
!define HOMELAND(_alias, _label) rectangle "<$map>\n_label" as _alias

!define RULES(_alias, _label) rectangle "<$book>\n_label" as _alias
!define SUBRULES(_alias, _label) rectangle "<$book_open>\n_label" as _alias
!define SUBORD(_alias, _label) rectangle "<$book_bookmark>\n_label" as _alias

!define SPELL(_alias, _label) rectangle "<$magic>\n_label" as _alias
!define POOL(_alias, _label) rectangle "<$thermometer>\n_label" as _alias


skinparam RectangleBorderColor  White
skinparam RectangleBackgroundColor  White

!$runefont = 'Glorantha Core Runes'



@enduml