@startuml

skinparam handwritten true
skinparam componentstyle rectangle
allowmixing
skinparam titleFontSize 18

skinparam actorStyle Hollow 
skinparam actorBackgroundColor black

!includeurl ../sprites/fire_sky.puml
!includeurl ../sprites/air.puml
!includeurl ../sprites/water.puml
!includeurl ../sprites/earth.puml
!includeurl ../sprites/darkness.puml
!includeurl ../sprites/movement_change.puml
!includeurl ../sprites/moon_full.puml

!$ICONURL = "../icons/icons"
!$SPRITEURL = "../sprites"

!include $ICONURL/common.puml
!includeurl $ICONURL/govicons/washington_monument.puml
!includeurl $ICONURL/font-awesome-6/crown.puml
!includeurl $ICONURL/font-awesome-6/landmark.puml
!includeurl $ICONURL/font-awesome-6/landmark_dome.puml
!includeurl $ICONURL/font-awesome-6/monument.puml
!includeurl $ICONURL/font-awesome-6/mosque.puml
!includeurl $ICONURL/font-awesome-6/place_of_worship.puml
!includeurl $ICONURL/font-awesome-6/tent.puml
!includeurl $ICONURL/font-awesome-6/people_group.puml
!includeurl $ICONURL/font-awesome-6/people_line.puml
!includeurl $ICONURL/font-awesome-6/book.puml
!includeurl $ICONURL/font-awesome-6/book_open.puml
!includeurl $ICONURL/font-awesome-6/book_bookmark.puml

!includeurl $ICONURL/font-awesome-6/map.puml
!includeurl $ICONURL/font-awesome-5/magic.puml
!includeurl $ICONURL/font-awesome/thermometer.puml
!includeurl $ICONURL/font-awesome/gears.puml
!includeurl $ICONURL/font-awesome-6/cow.puml
!includeurl $ICONURL/font-awesome-6/horse.puml
!includeurl $ICONURL/font-awesome-6/coins.puml
!includeurl $ICONURL/font-awesome-6/scroll.puml
!includeurl $ICONURL/font-awesome-6/masks_theater.puml
!includeurl $ICONURL/font-awesome-6/fish.puml
!includeurl $ICONURL/material/local_hospital.puml
!includeurl $ICONURL/font-awesome-5/ghost.puml
!includeurl $ICONURL/font-awesome-6/graduation_cap.puml
!includeurl $ICONURL/font-awesome-6/wheat_awn.puml
!includeurl $ICONURL/font-awesome-6/mask.puml
!includeurl $ICONURL/font-awesome-6/mountain.puml

!includeurl $SPRITEURL/1h-sword.puml
!includeurl $SPRITEURL/arrows.puml
!includeurl $SPRITEURL/knife.puml


!define SHRINE(_alias, _label, _color) rectangle "<$monument*.7,color=_color>\n_label" as _alias
!define MINOR(_alias, _label, _color) rectangle "<$landmark,color=_color>\n_label" as _alias
!define MAJOR(_alias, _label, _color) rectangle "<$landmark_dome*1.4,color=_color>\n_label" as _alias
!define GREAT(_alias, _label, _color) rectangle "<$place_of_worship*2,color=_color>\n_label" as _alias

!define SHRINE(_alias, _label) SHRINE(_alias, _label, CadetBlue)
!define MINOR(_alias, _label) MINOR(_alias, _label, CadetBlue)
!define MAJOR(_alias, _label) MAJOR(_alias, _label, CadetBlue)
!define GREAT(_alias, _label) GREAT(_alias, _label, CadetBlue)

!define SHRINE(_alias) SHRINE(_alias, "_alias")
!define MINOR(_alias) MINOR(_alias, "_alias")
!define MAJOR(_alias) MAJOR(_alias, "_alias")
!define GREAT(_alias) GREAT(_alias, "_alias")


!define CLAN(_alias, _label) rectangle "<$people_group>\n_label" as _alias
!define TRIBE(_alias, _label) rectangle "<$people_line>\n_label" as _alias
!define HOMELAND(_alias, _label) rectangle "<$map>\n_label" as _alias

!define RULES(_alias, _label) rectangle "<$book>\n_label" as _alias
!define SUBRULES(_alias, _label) rectangle "<$book_open>\n_label" as _alias
!define SUBORD(_alias, _label) rectangle "<$book_bookmark>\n_label" as _alias

!define SPELL(_alias, _label) rectangle "<$magic>\n_label" as _alias
!define POOL(_alias, _label) rectangle "<$thermometer>\n_label" as _alias


!define GUILD(_alias) rectangle "<$gears,color=DarkGrey>\n_alias" as _alias
!define HERDER(_alias) rectangle "<$cow,color=DarkGrey>\n_alias" as _alias
!define HERDER2(_alias) rectangle "<$horse,color=DarkGrey>\n_alias" as _alias
!define MERCHANT(_alias) rectangle "<$coins,color=DarkGrey>\n_alias" as _alias
!define SCRIBE(_alias) rectangle "<$scroll,color=DarkGrey>\n_alias" as _alias
!define ENTERTAINER(_alias) rectangle "<$masks_theater,color=DarkGrey>\n_alias" as _alias
!define NOBLE(_alias) rectangle "<$crown,color=DarkGrey>\n_alias" as _alias
!define FISHER(_alias) rectangle "<$fish,color=DarkGrey>\n_alias" as _alias
!define HEALER(_alias) rectangle "<$local_hospital,color=DarkGrey>\n_alias" as _alias
!define SHAMAN(_alias) rectangle "<$ghost,color=DarkGrey>\n_alias" as _alias
!define WARRIOR(_alias) rectangle "<$1h-sword*2.5,color=DarkGrey>\n_alias" as _alias
!define HUNTER(_alias) rectangle "<$arrows*2,color=DarkGrey>\n_alias" as _alias
!define THIEF(_alias) rectangle "<$knife*2,color=DarkGrey>\n_alias" as _alias
!define PHILOSOPHER(_alias) rectangle "<$graduation_cap,color=DarkGrey>\n_alias" as _alias
!define FARMER(_alias) rectangle "<$wheat_awn,color=DarkGrey>\n_alias" as _alias
!define BANDIT(_alias) rectangle "<$mask,color=DarkGrey>\n_alias" as _alias
!define MOUNTAINEER(_alias) rectangle "<$mountain,color=DarkGrey>\n_alias" as _alias
!define CHARIOTEER(_alias) rectangle "<$movement_change*2,color=DarkGrey>\n_alias" as _alias


skinparam RectangleBorderColor  White
skinparam RectangleBackgroundColor  White

!$runefont = 'Glorantha Core Runes'



@enduml