@startuml
sprite $arrow [16x16/16] {
00FF0FFFFFFFFFFF
00FF0FFFFFFFFFFF
FFFFF0FFFFFFFFFF
0FFFF00FFFFFFFFF
00FFFF00FFFFFFF0
FF00FFF0FFFFFFF0
FFF00FFF0FFFFFF0
FFFF00FFF0FFFFF0
FFFFFF0FFF0FFFF0
FFFFFFF0FFFFFF00
FFFFFFFFFFFF0F00
FFFFFFFFFFFFFF00
FFFFFFFFFF0FFFF0
FFFFFFFFFFFFFFF0
FFFFFFFFF000FFFF
FFF00000000000FF
}
@enduml
