@startuml
sprite $cold [16x16/16] {
0000FFFFFFFF0000
00FFFFFFFFFFFF00
00FFFFFFFFFFFFF0
FFFFFFFFFFFFFFF0
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFF00FFFFFFF
FFFFFFF00FFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
0FFFFFFFFFFFFFF0
00FFFFFFFFFFFFF0
000FFFFFFFFFFF00
0000FFFFFFFF0000
}
@enduml
