@startuml
sprite $disorder [38x64/16] {
FFFFFFFFFFFFF000000000000FFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
0000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
0000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
000000000FFFFFFFFFFFFFFFFFFFFFF0000000
000000000FFFFFFFFFFFFFFFFFFFFFF0000000
0000000FFFFFFFFFFFFFFFFFFFFFF000000000
0000000FFFFFFFFFFFFFFFFFFFFFF000000000
0000000FFFFFFFFFFFFFFFFFFFFFFFF0000000
0000000FFFFFFFFFFFFFFFFFFFFFFFF0000000
0000000FFFFFFFFFFFFFFFFFFFFFFFF0000000
0000000FFFFFFFFFFFFFFFFFFFFFFFF0000000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFF000000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00000FFFFFFFFFFFFFF00FFFFFFFFFFFF00000
00000FFFFFFFFFFFFFF00FFFFFFFFFFFF00000
00000FFFFFFFFFFFFF000FFFFFFFFFFFF00000
00000FFFFFFFFFFFF0000FFFFFFFFFFFF00000
00000FFFFFFFFFFFF0000FFFFFFFFFFFF00000
00000FFFFFFFFFFFF0000FFFFFFFFFFFF00000
00000FFFFFFFFFFFF0000FFFFFFFFFFFF00000
00000FFFFFFFFFFFF0000FFFFFFFFFFFF00000
00000FFFFFFFFFFFF0000FFFFFFFFFFFF00000
00000FFFFFFFFFFFF0000FFFFFFFFFFFF00000
00000FFFFFFFFFFFF0000FFFFFFFFFFFF00000
00000FFFFFFFFFFFF0000FFFFFFFFFFFF00000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
000000FFFFFFFFFFFFFFFFFFFFFFFFFFF00000
0000000FFFFFFFFFFFFFFFFFFFFFFFFFF00000
0000000FFFFFFFFFFFFFFFFFFFFFFFFFF00000
0000000FFFFFFFFFFFFFFFFFFFFFFFF0000000
0000000FFFFFFFFFFFFFFFFFFFFFFFF0000000
000000000FFFFFFFFFFFFFFFFFFFFFF0000000
000000000FFFFFFFFFFFFFFFFFFFFFF0000000
000000000FFFFFFFFFFFFFFFFFFFF000000000
000000000FFFFFFFFFFFFFFFFFFFF000000000
0000000FFFFFFFFFFFFFFFFFFFFFFFFFF00000
0000000FFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFF
FFFFFFFFFFF0000000000000000FFFFFFFFFFF
}
@enduml
