@startuml
sprite $disorder [9x16/16] {
FFFF0FFFF
FFFFFFFFF
FFFFFFFFF
00FFFFF00
00FFFFF00
0FFFFFFF0
0FFF0FFF0
0FFF0FFF0
0FFF0FFF0
0FFF0FFF0
0FFFFFFF0
00FFFFF00
00FFFFF00
FFFFFFFFF
FFFFFFFFF
FFFF0FFFF
}
@enduml
