@startuml
sprite $dragon [16x16/16] {
FF0000FFFF000FF0
FFF00FFFFF00FFF0
FFFFFFFFFFFFFFF0
0FFFFFFFFFFFFF00
00FFFFF00FFFF000
0FFFFFF0FFFFFF00
FFFFFFFFFFFFFFF0
FFFF0FFFFF00FFFF
FFF00FFFFF00FFFF
FFFFFFFFFFFFFFF0
0FFFFFF0FFFFFF00
00FFFFF00FFFFF00
0FFFFFF0FFFFFFF0
FFFFFFFFFFFFFFF0
FFF00FFFFFF0FFF0
0F0000FFF0000FF0
}
@enduml
