@startuml
sprite $fire_sky_2 [15x16/16] {
0000FFFFFFF0000
000FFFFFFFFFF00
0FFFFFFFFFFFF00
0FFFFF000FFFFF0
FFFF000000FFFFF
FFFF0FFFF00FFFF
FFF0FFFFFF00FFF
FFF0FFFFFF00FFF
FFF0FFF0FF00FFF
FFF00FFFFF00FFF
FFFF0FFFFF0FFFF
FFFF00FF000FFFF
0FFFFF000FFFFF0
0FFFFFFFFFFFFF0
00FFFFFFFFFFF00
0000FFFFFFFF000
}
@enduml
