@startuml
sprite $harmony [15x16/16] {
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
FFF00FFFF00FFFF
}
@enduml
