@startuml
sprite $large-shield [16x16/16] {
000FFFFFFFFFF000
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
000FFFFFFFFFF000
}
@enduml
