@startuml
sprite $lightbringers [46x64/16] {
000000000FFFFFFFFFFFFFFFFFFFF00000000000000000
0000000FFFFFFFFFFFFFFFFFFFFFF00000000000000000
0000000FFFFFFFFFFFFFFFFFFFFF000000000000000000
00000FFFFFFFFFFFFFFFFFFFFFF0000000000000000000
00000FFFFFFFFFFFFFFFFFFFFFF0000000000000000000
000FFFFFFFFFFFFFFFFFFFFFFFF0000000000000000000
000FFFFFFFFFFFFFFFFFFFFFFFF0000000000000000000
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000000
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000
000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000
000000000FFFFFFFFFFFFFFFFFFFFFFFFFF00000000000
000000000FFFFFFFFFFFFFFFFFFFFFFFFFF00000000000
0000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000
0000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
0FFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFF0
FFFFFFFFFFFFFFF00FFFFFFFFFFFF00FFFFFFFFFFFFFF0
FFFFFFFFFFFFFFF00FFFFFFFFFFFF00FFFFFFFFFFFFFF0
FFFFFFFFFFFFF0000FFFFFFFFFFFF0000FFFFFFFFFFFFF
FFFFFFFFFFFFF0000FFFFFFFFFFFF0000FFFFFFFFFFFFF
FFFFFFFFFFF000000FFFFFFFFFFFF0000FFFFFFFFFFFFF
FFFFFFFFFFF000000FFFFFFFFFFFF00000FFFFFFFFFFFF
FFFFFFFFFFF000000FFFFFFFFFFFF000000FFFFFFFFFFF
FFFFFFFFFFF000000FFFFFFFFFFFF000000FFFFFFFFFFF
FFFFFFFFF00000000FFFFFFFFFFFF000000FFFFFFFFFFF
FFFFFFFFF00000000FFFFFFFFFFFF000000FFFFFFFFFFF
FFFFFFFFF00000000FFFFFFFFFFFF0000000FFFFFFFFFF
FFFFFFFFF00000000FFFFFFFFFFFF000000FFFFFFFFFFF
FFFFFFFFF00000000FFFFFFFFFFFF000000FFFFFFFFFFF
FFFFFFFFF00000000FFFFFFFFFFFF0000000FFFFFFFFFF
FFFFFFFFF00000000FFFFFFFFFFFF00000000FFFFFFFFF
}
@enduml
