@startuml
sprite $lightbringers [11x16/16] {
00FFFFF0000
0FFFFF00000
FFFFFFFFF00
FFFFFFFFF00
FFFFFFFFFF0
FFFFFFFFFF0
FFFFFFFFFF0
FFFFFFFFFF0
0FFFFFFFF00
00FFFFFF000
0FFFFFFFFF0
FFFFFFFFFF0
FFFFFFFFFFF
FFF0FFF0FFF
FF00FFF0FFF
FF00FFF00FF
}
@enduml
