@startuml
sprite $mastery [16x16/16] {
FFFF00000000FFFF
FFFF00000000FFFF
FFFF00000000FFFF
FFFF00000000FFFF
FFFF00000000FFFF
FFFF00FFFF00FFFF
FFFF00FFFF00FFFF
FFFF00FFFF00FFFF
FFFF00FFFF00FFFF
FFFF00FFFF00FFFF
FFFF00FFFF00FFFF
FFFF00FFFF00FFFF
FFFFF0FFFFF0FFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
}
@enduml
