@startuml
sprite $medium-shield [16x16/16] {
000000FFFF000000
0000FFFFFFFF0000
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
0FFFFFFFFFFFFFF0
0FFFFFFFFFFFFFF0
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
0FFFFFFFFFFFFFF0
0FFFFFFFFFFFFFF0
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
0000FFFFFFFF0000
000000FFFF000000
}
@enduml
