@startuml
sprite $moon_empty_half [16x16/16] {
00000FFFFFFF0000
00FFFFFFFFFFF000
0FFFFFFFFFFFFF00
0FFFFFFFF0FFFFF0
FFFFFFFF000FFFFF
FFFFFFFF0000FFFF
FFFFFFFF0000FFFF
FFFFFFFF00000FFF
FFFFFFFFF0000FFF
FFFFFFFFF000FFFF
FFFFFFFF0000FFFF
FFFFFFFF0000FFFF
0FFFFFFF00FFFFF0
0FFFFFFFFFFFFF00
00FFFFFFFFFFF000
000F0FFFFFFF0000
}
@enduml
