@startuml
sprite $moon_crescent_go [16x16/16] {
00000FFFFFF00000
00FFFFFFFFFFF000
0FFFFFFFFFFFFF00
0FFFFFFFFFFFFFF0
FFFFF0FFFFFFFFFF
FFFF0FFFFFFFFFFF
FFF00FFFFFFFFFFF
FFF00FFFFFFFFFFF
FFF00FFFFFFFFFFF
FFF00FFFFFFFFFFF
FFFF0FFFFFFFFFFF
FFFFF0FFFFFFFFFF
0FFFFFFFFFFFFFF0
0FFFFFFFFFFFFF00
00FFFFFFFFFFF000
00000FFFFFFF0000
}
@enduml
