@startuml
sprite $moon_crescent_come [16x16/16] {
00000FFFFFFF0000
00FFFFFFFFFFF000
0FFFFFFFFFFFFF00
0FFFFFFFFFFFFFF0
FFFFFFFFFF0FFFFF
FFFFFFFFFFF0FFFF
FFFFFFFFFFF0FFFF
FFFFFFFFFFF00FFF
FFFFFFFFFFF00FFF
FFFFFFFFFFF0FFFF
FFFFFFFFFFF0FFFF
FFFFFFFFFF00FFFF
0FFFFFFFFFFFFFF0
0FFFFFFFFFFFFF00
00FFFFFFFFFFF000
000F0FFFFFFF0000
}
@enduml
