@startuml
sprite $moon_full_half [16x16/16] {
00000FFFFFF00000
00FFFFFFFFFFF000
0FFFFFFFFFFFFF00
0FFFFFFFFFFFFFF0
FFFFF00FFFFFFFFF
FFFF000FFFFFFFFF
FFF0000FFFFFFFFF
FFF0000FFFFFFFFF
FFF0000FFFFFFFFF
FFF0000FFFFFFFFF
FFFF000FFFFFFFFF
FFFFF00FFFFFFFFF
0FFFFFFFFFFFFFF0
0FFFFFFFFFFFFF00
00FFFFFFFFFFF000
00000FFFFFFF0000
}
@enduml
