@startuml
sprite $moon_black [16x16/16] {
0000FFFFFFFF0000
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
0FFFFFFFFFFFFFF0
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFF0
0FFFFFFFFFFFFFF0
00FFFFFFFFFFF000
0000FFFFFFFF0000
}
@enduml
