@startuml
sprite $stone-sphere [16x16/16] {
00000FFFFF000000
000FFFFFFFFF0000
00FFFFFFFFFFFF00
0FFFFFFFFFFFFFF0
0FFFFFFFFFFFFFF0
FFFFFFFFFFFFFFF0
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
0FFFFFFFFFFFFFF0
00FFFFFFFFFFFF00
00FFFFFFFFFFFF00
000FFFFFFFFFF000
00000FFFFFF00000
}
@enduml
