@startuml
sprite $undeath [16x16/16] {
F00000FFFF0000FF
FF0000FFFF000FFF
FFFF00FFFF00FFFF
FFFFF0FFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFF0FFFFFFFF0FFF
FFF0FFFFFFFF0FFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF
FFFFFFFFFF0FFFFF
FFFF00FFFF00FFFF
FFF000FFFF0000FF
FF0000FFFF00000F
}
@enduml
